config/routes.rb
Rails.application.routes.draw do
  resources :schools, only: [:index, :new, :create, :show]

  root to: 'schools#index' 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/school.rb
class School < ApplicationRecord
  geocoded_by :address
  after_validation :geocode, if: ->(obj){ obj.address.present? and obj.address_changed? }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  def index
    @schools = School.all
    @hash = Gmaps4rails.build_markers(@schools) do |school, marker|
      marker.infowindow "<b>#{school.name}</b><p>#{school.address}</p>"
      marker.lat school.latitude
      marker.lng school.longitude
    end
    if params[:center] && params[:center] != ''
      center = params[:center]
      lat = Geocoder.search(center).first.coordinates.first
      lng = Geocoder.search(center).first.coordinates.last
      @center_on = [lat, lng]
    else
      @center_on = [45.543897, -122.655977]
    end
  end

  def new
    @school = School.new
  end

  def create
    @school = School.new(school_params)
    if @school.save
      flash[:notice] = "You have saved a new school!"
      redirect_to root_path
    else
      flash[:alert] = "You have not saved a new school."
      render :new
    end
  end

  def show
    @school = School.find(params[:id])
  end

private
  def school_params
    params.require(:school).permit(:name, :address)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GmapsPractice</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="//maps.google.com/maps/api/js?key=<%=ENV['GOOGLE_API_KEY']%>"></script>
    <script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
    <script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/schools/index.html.erb
<h1>Index</h1>
<%= form_tag schools_path, method: 'get', role: 'search' do %>
  <%= text_field_tag :center, params[:center], class: 'form-control', id: 'center-map' %>
  <%= submit_tag 'Search', name: nil, class: 'btn btn-primary' %>
<% end %>
<div style='width: 800px;'>
  <div id="map" style='width: 800px; height: 400px;'></div>
</div>

<% @schools.each do |school| %>
  <li><strong><%= link_to school.name, school_path(school) %></strong> Lat: <%= school.latitude %>, Long: <%= school.longitude %></li>
<% end %>
<%= link_to 'Add a New School', new_school_path, class: 'btn btn-primary' %>

<script type="text/javascript">
  handler = Gmaps.build('Google');
  handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
    markers = handler.addMarkers(<%= raw @hash.to_json %>);
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
    handler.map.centerOn(<%= @center_on %>);
    handler.getMap().setZoom(12);
  });
</script>

app/views/schools/new.html.erb
<h1>Add a New School</h1>
<%= form_for @school do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :address %>
  <%= f.text_field :address %>
  <%= f.submit 'Add School', class: 'btn btn-primary' %>
<% end %>

app/views/schools/show.html.erb
<%= @school.name %>
<%= @school.address %>

<%= image_tag "http://maps.googleapis.com/maps/api/staticmap?center=#{@school.latitude},#{@school.longitude}&markers=#{@school.latitude},#{@school.longitude}&zoom=15&size=640x400&key=#{ENV['GOOGLE_API_KEY']}",
              class: 'img-fluid', alt: "#{@school.name} on the map"%>